[package]
edition = "2021"
name = "profiles_integrity"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profiles_integrity"

[dependencies]
hdi = "=0.2.4"
holo_hash = { version = "=0.1.4", features = ["encoding"] }
serde = "=1.0.164"
